#! /bin/sh

export QT_STYLE_OVERRIDE=kvantum
export QT_QPA_PLATFORMTHEME=qt5ct
#export KDE_FULL_SESSION=true
#export XDG_CURRENT_DESKTOP=KDE

pgrep -x sxhkd >/dev/null || sxhkd &

xrandr --output DP-0 --primary --mode 3440x1440 --rotate normal --output HDMI-0 --mode 1920x1080 --right-of DP-0 --rotate right 

bspc config border_width 2
bspc config window_gap 16
bspc config focus_follows_pointer true

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

source $HOME/.config/bspwm/colors/current_color.sh

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Nitrogen state=floating
bspc rule -a dolphin state=floating

bspc monitor DP-0 -d code office graphics web media chat files misc extra

barriers -c $HOME/.local/share/barrier/barrier.conf -d INFO -f --daemon --disable-crypto 
picom --backend glx --config $HOME/.config/picom/picom.conf &

polybar &
nitrogen --restore &
